### PR TITLE
Fix a bug where spirit-specific setup items didn't work if moved to the wrong spirit first.

### PR DESCRIPTION
**Pull request by pyrrhicPachyderm**
Namely, Days That Never Were, Deep Slumber, Sunshine, and Immense. If the object was moved to the wrong spirit's play area first, it would broadcast the message that it was the wrong spirit, but the object would still have its setupComplete variable marked as true. as such, explicitly set setupComplete to false if setup fails due to being in the wrong spirit's area.

### CODE REVIEW

**Comment by pyrrhicPachyderm** [comment]
Och, that's a fair warning from the linter. I've seen other points in the code where you suppress that warning, but it is admittedly fairly unclear what the code I've added here is doing.

The other way I'd thought of handling this was to have `doSetup()` return false if it failed, and have the places that call `doSetup()` *not* set `setupComplete` if they receive an explicit false return. That shouldn't break any custom spirits/aspects with `doSetup()` functions, 'cause if they continue the current behaviour of never returning anything, then that won't be an explicit false, and things will remain as they are.

Would that solution be preferable?

**Comment by iakona** [comment]
so to make the linter happy all you'd have to do is add a `setupComplete = false` at top of the file

as for this change itself, i'm thinking either we have `doSetup()` return a boolean like you suggested and then have global script set `setupComplete` to the return value. or we just move changing of `setupComplete` into the function itself. i'd prefer the former though since for custom content it'd be a bit harder for folks to make mistake

**Comment by pyrrhicPachyderm** [comment]
I've changed the return value of `doSetup()`. Frankly, this would be a pretty rare bug to come up in the first place (it's a bit odd to put aspects in the wrong spirit's play area first), so I don't think it's at all urgent to get this in.

**Comment by iakona** [comment]
so yea in general this looks good, just waiting to commit this until i'm working on a new minor release

**Pull request merged**
