### PR TITLE
Show the current mod version.

### PR DESCRIPTION
**Pull request by dewiniaid**
- Adds a "version ???" 3DText object underneath the "Spirit Island [By MJ & iakona]" text.
- onLoad() sets the above text to use the version defined in the Global Lua script.
- Repositioned text objects slightly to fit the new text addition.

### CODE REVIEW

**Comment by dewiniaid** [comment]
Turns out I was a bit overzealous when removing things that shouldn't have been committed.  Also turns out that `tts repack` really wants a list of all indexes of what to pack and isn't smart enough to just scan the objects folder.

**Comment by iakona** [comment]
why not have this tied into existing 3d text?

**Comment by GS-Yusri** [comment]
As in, simply having a plain 3D text object with the version rather than having it set onLoad() and such?  I considered it, this feels easier to update though to me.

As in simply tacking it onto an existing 3D text object?  They needed to be moved anyways, and this allowed for making the version text a little more subtle than the existing text (i.e. smaller, or a grey instead of a white).

**Comment by iakona** [comment]
can you change this to point at beta branch instead? and then I'll approve this

**Review by iakona — APPROVED** [review]

**Pull request merged**
