### PR TITLE
Ignore beasts in player areas for Russia's loss condition.

### PR DESCRIPTION
**Pull request by pyrrhicPachyderm**
For Unconstrained Fangs' prepared beasts.

### CODE REVIEW

**Comment by iakona** [comment]
What if a player puts the endless dark tile in their player area?

**Comment by pyrrhicPachyderm** [comment]
Hmm, that's a good point. Accounting for that would require raycasting from each beast. At which point, it might as well raycast from every beast to see if it's on an island, and forget about zones at all. I assume a raycast-based solution was being avoided for performance reasons, but the presence loss condition is already raycasting from presence, and there'll usually be a lot more presence than beasts, so hopefully it won't be too bad.

I'm happy to implement that if you think that'd be best. Will probably wait for #125 first, though.

**Comment by pyrrhicPachyderm** [comment]
It occurs to me that, if the Endless Dark being placed in the player area is to be supported, `checkPresenceLoss()` also needs to not ignore presence in the player area.

**Comment by iakona** [comment]
so thinking about unconstrained some more, i'd probably implement it as a UI tracker and then a button to cash out and generate a stack of beasts. now that being said, there'd still be a problem with breath of darkness incarna being destroyed/off the island and how to properly account for that (which could be the solution you proposed here)

**Comment by iakona** [comment]
in theory you could iterate through each object tagged as beasts and if it's also tagged as presence then do a raycast to see if it's ontop of an island

**Comment by pyrrhicPachyderm** [comment]
So, to summarise, two options:
- Have every beast raycast to see if it's on an island.
- Give Unconstrained a bag to keep its beasts in, and handle beast Incarna specially.
The latter would obviously be faster, but it's also more robust to people doing weird things (loose beasts, or choosing not use Unconstrained's bag). I'll do some benchmarking to see *how* much slower the first option is.

Also, a side-note: if you do add an Unconstrained bag with a cash-out button, bear in mind that Unconstrained is allowed to cash out only *some* of its prepared beasts on a given turn (and might have a valid reason to do so if it doesn't need them all for Ranging Hunt damage on a given turn, and wants to save them for a larger instance of damage far away on a subsequent turn).

**Comment by pyrrhicPachyderm** [comment]
Alright, wrote a function for benchmarking. Tested it with 57 beasts on the board (this is as many as you can have in a physical copy, with both JE & B&C, so it seems a reasonable upper bound). It takes just shy of 0.01 seconds on my computer. That shouldn't be enough to prevent 60 FPS, and Russia loss condition check is only scheduled to run every five seconds, so that seems fairly reasonable to me. What do you reckon; shall I go ahead with this solution?
```function benchmark()
    local startTime
    local endTime
    local n = 100
    local beastPiles = 0
    
    startTime = os.clock()
    for it = 1,n do
        for _,obj in pairs(getObjectsWithTag("Beasts")) do
            local isCounted = (obj.held_by_color ~= nil)
            if not isCounted then
                local hits = Physics.cast({
                    origin = obj.getBounds().center,
                    direction = Vector(0,-1,0),
                    max_distance = 2,
                })
                for _,v in pairs(hits) do
                    if v.hit_object ~= obj and Global.call("isIsland", {obj=v.hit_object}) then
                        isCounted = true
                        break
                    end
                end
            end
            if isCounted then
                beastPiles = beastPiles + 1
            end
        end
    end
    endTime = os.clock()
    
    log("Beast piles: "..beastPiles/n)
    log("Time: "..(endTime - startTime)/n)
end```

**Comment by iakona** [comment]
sorry for not getting around to this sooner, lets go ahead and have it do the raycast to check if it's on the island while in player areas

**Comment by pyrrhicPachyderm** [comment]
Had to rebase this onto `beta`, to get access to `isIsland()` from #125.

**Pull request merged**
